# ~/.config/starship.toml
# format = "$all"
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$env_var\
$crystal\
$custom\
$sudo\
$time\
$status\
$container\
$shell\
$line_break\
$character$time"""


# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[c]
format = "via [$name $version]($style)"

[directory]
truncation_length = 5
truncation_symbol = "…/"

[username]
style_user = "yellow"
style_root = "black bold"
format = "[$user]($style): "
disabled = false
show_always = true

[git_commit]
commit_hash_length = 6
tag_symbol = "🔖 "

[git_status]
staged = '[+ \($count\)](green)'



